spring.application.name=portal

server.port=8080

#banco
spring.datasource.url=jdbc:postgresql://localhost:5432/senai_db
spring.datasource.username=admin
spring.datasource.password=549521

#realiza alterações no banco de dados de acordo com o codigo
spring.jpa.hibernate.ddl-auto=update
#mostrar as consultas sql que estão sendo executadas no banco de dados
spring.jpa.show-sql=true
#formatar as consultas sql que estão sendo executadas no banco de dados
spring.jpa.properties.hibernate.format_sql=true
#intervalo de tempo para verificar se houve alterações no código
spring.devtools.restart.poll-interval=2s
#periodo de tempo em que o programa fica "quieto" antes de reiniciar
spring.devtools.restart.quiet-period=1s
